export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const REGISTER_PENDING = 'REGISTER_PENDING';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
