export const FETCH_USER_SETTINGS_PENDING = 'FETCH_USER_SETTINGS_PENDING';
export const FETCH_USER_SETTINGS_SUCCESS = 'FETCH_USER_SETTINGS_SUCCESS';
export const FETCH_USER_SETTINGS_ERROR = 'FETCH_USER_SETTINGS_ERROR';

export const UPDATE_USER_SETTINGS_PENDING = 'UPDATE_USER_SETTINGS_PENDING';
export const UPDATE_USER_SETTINGS_SUCCESS = 'UPDATE_USER_SETTINGS_SUCCESS';
export const UPDATE_USER_SETTINGS_ERROR = 'UPDATE_USER_SETTINGS_ERROR';
